name: vietmap_automotive_flutter
description: "A Flutter plugin for integrating turn by turn navigation with Vietmap Android Auto and Vietmap Apple CarPlay SDK."
version: 0.0.3-pre.1
homepage: https://maps.vietmap.vn
repository: https://github.com/vietmap-company/vietmap_automotive_flutter
issue_tracker: https://github.com/vietmap-company/vietmap_automotive_flutter/issues
documentation: https://maps.vietmap.vn

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter: 
  plugin:
    platforms:
      android:
        package: vn.vietmap.vietmap_automotive_flutter
        pluginClass: VietmapAutomotiveFlutterPlugin
      ios:
        pluginClass: VietmapAutomotiveFlutterPlugin
 
topics:
  - automotive
  - android-auto
  - apple-carplay
  - turn-by-turn-navigation
  - vietmap