name: Generate docs

on:
  push:
      branches: [ main ]

jobs:
  generate-docs:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.12.0
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          channel: 'stable'
          cache: true

      - name: Install dartdoc
        run: flutter pub global activate dartdoc
        
      - run: flutter pub get
      
      - name: Generate docs
        run: flutter pub global run dartdoc --output docs

      - name: Push docs
        run: |
          git config --global user.name "VietMap Docs Bot"
          git config --global user.email "docs-bot-vietmap-automotive-flutter@localhost"
          git branch docs
          git add -f docs
          git commit -m "docs: ${{ github.event.commits[0].id }}"
          git push --force origin ${{ github.head_ref || github.ref_name }} :docs